/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.car;

import java.io.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

import com.iot.nero.smartcan.entity.Platoon;
public enum DRIVEBEHAVIOR {
	inmiddle(0),
	inleft(1),
	inright(2),
	lefttomiddle(3),
	middletoleft(4),
	righttomiddle(5),
	middletoright(6);

	public static DRIVEBEHAVIOR valueOf(int value){
		DRIVEBEHAVIOR[] values = values();
		for(int i=0;i<values.length;i++){
			if(values[i].value==value){
				return values[i];
			}
		}
		 throw new IllegalArgumentException("No enum const value for " + value);
	}


	private int value;

	private DRIVEBEHAVIOR(int value) {
		this.value = value;
	}

	public int value(){
		return value;
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static DRIVEBEHAVIOR ber_decode(InputStream in) throws IOException {
		return (DRIVEBEHAVIOR)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65607);

	public final static AsnConverter CONV;

	static {
		CONV = new ReflectionEnumeratedConverter(DRIVEBEHAVIOR.class);
	}


}
