/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.car;

import java.io.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

import com.iot.nero.smartcan.entity.Platoon;
public class Position3D {

	@NotNull
	@Component(0)
	public Double longitude;

	@NotNull
	@Component(1)
	public Double latitude;

	@NotNull
	@Component(2)
	public Double velocity;

	@NotNull
	@Component(3)
	public Double yaw;

	@NotNull
	@Component(4)
	public Double altitude;

	@NotNull
	@Component(5)
	public byte[] gpsUtime;


	public boolean equals(Object obj) {
		if(!(obj instanceof Position3D)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static Position3D ber_decode(InputStream in) throws IOException {
		return (Position3D)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65543);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(Position3D.class);
		AsnConverter longitudeConverter = FLOAT.CONV;
		AsnConverter latitudeConverter = FLOAT.CONV;
		AsnConverter velocityConverter = FLOAT.CONV;
		AsnConverter yawConverter = FLOAT.CONV;
		AsnConverter altitudeConverter = FLOAT.CONV;
		AsnConverter gpsUtimeConverter = TimeStamp.CONV;
		CONV.setComponentConverters(new AsnConverter[] { longitudeConverter, latitudeConverter, velocityConverter, yawConverter, altitudeConverter, gpsUtimeConverter });
	}


}
