/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.car;

import java.io.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import com.iot.nero.smartcan.entity.Platoon;

public class Position3D {

	@NotNull
	@Component(0)
	public Double x;

	@NotNull
	@Component(1)
	public Double y;

	@NotNull
	@Component(2)
	public Double z;


	public boolean equals(Object obj) {
		if(!(obj instanceof Position3D)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static Position3D ber_decode(InputStream in) throws IOException {
		return (Position3D)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65544);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(Position3D.class);
		AsnConverter xConverter = DoubleConverter.INSTANCE;
		AsnConverter yConverter = DoubleConverter.INSTANCE;
		AsnConverter zConverter = DoubleConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { xConverter, yConverter, zConverter });
	}


}
