/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.car;

import java.io.*;
import java.util.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import com.iot.nero.smartcan.entity.Platoon;

public class SmartCarRequestBody {

	@NotNull
	@Component(0)
	public Long msgCnt;

	@NotNull
	@Component(1)
	public byte[] token;

	@NotNull
	@Component(2)
	public Boolean isautodrive;

	@NotNull
	@Component(3)
	public Vector<Wiper> wipers;

	@NotNull
	@Component(4)
	public Vector<Light> lights;

	@NotNull
	@Component(5)
	public Vector<Running> runnings;

	@NotNull
	@Component(6)
	public Vector<Safety> safetys;

	@NotNull
	@Component(7)
	public Vector<Other> others;


	public boolean equals(Object obj) {
		if(!(obj instanceof SmartCarRequestBody)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static SmartCarRequestBody ber_decode(InputStream in) throws IOException {
		return (SmartCarRequestBody)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65596);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(SmartCarRequestBody.class);
		AsnConverter msgCntConverter = MsgCount.CONV;
		AsnConverter tokenConverter = Token.CONV;
		AsnConverter isautodriveConverter = BooleanConverter.INSTANCE;
		AsnConverter wipersConverter = WiperList.CONV;
		AsnConverter lightsConverter = LightList.CONV;
		AsnConverter runningsConverter = RunningList.CONV;
		AsnConverter safetysConverter = SafetyList.CONV;
		AsnConverter othersConverter = OthersList.CONV;
		CONV.setComponentConverters(new AsnConverter[] { msgCntConverter, tokenConverter, isautodriveConverter, wipersConverter, lightsConverter, runningsConverter, safetysConverter, othersConverter });
	}


}
