/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.car;

import java.io.*;
import java.math.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

import com.iot.nero.smartcan.entity.Platoon;
public class SmartControlRequestMessage {

	@NotNull
	@Component(0)
	public Long msgCnt;

	@NotNull
	@Component(1)
	public byte[] token;

	@NotNull
	@Size(min=8, max=8)
	@Component(2)
	public byte[] vid;

	@NotNull
	@Component(3)
	public Double steering;

	@NotNull
	@Component(4)
	public Double throttle;

	@NotNull
	@Component(5)
	public TransmissionState transmission;

	@NotNull
	@Component(6)
	public ExteriorLights lights;

	@NotNull
	@Component(7)
	public Double brakePedal;

	@NotNull
	@Component(8)
	public HornStatus horn;

	@NotNull
	@Component(9)
	public byte[] timestamp;

	@NotNull
	@Component(10)
	public Long syncNum;


	public boolean equals(Object obj) {
		if(!(obj instanceof SmartControlRequestMessage)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static SmartControlRequestMessage ber_decode(InputStream in) throws IOException {
		return (SmartControlRequestMessage)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65610);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(SmartControlRequestMessage.class);
		AsnConverter msgCntConverter = MsgCount.CONV;
		AsnConverter tokenConverter = Token.CONV;
		AsnConverter vidConverter = OctetStringConverter.INSTANCE;
		AsnConverter steeringConverter = SteeringWheelAngle.CONV;
		AsnConverter throttleConverter = ThrottlePedal.CONV;
		AsnConverter transmissionConverter = TransmissionState.CONV;
		AsnConverter lightsConverter = ExteriorLights.CONV;
		AsnConverter brakePedalConverter = BrakePedalStatus.CONV;
		AsnConverter hornConverter = HornStatus.CONV;
		AsnConverter timestampConverter = TimeStamp.CONV;
		AsnConverter syncNumConverter = LongConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { msgCntConverter, tokenConverter, vidConverter, steeringConverter, throttleConverter, transmissionConverter, lightsConverter, brakePedalConverter, hornConverter, timestampConverter, syncNumConverter });
	}


}
