/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.car;

import java.io.*;
import java.math.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

import com.iot.nero.smartcan.entity.Platoon;
public class SmartStrategyRequestMessage {

	@NotNull
	@Component(0)
	public Long msgCnt;

	@NotNull
	@Component(1)
	public byte[] token;

	@NotNull
	@Size(min=8, max=8)
	@Component(2)
	public byte[] vid;

	@NotNull
	@Component(3)
	public DRIVEBEHAVIOR drivebehavior;

	@NotNull
	@Component(4)
	public Double movingdiss;

	@NotNull
	@Component(5)
	public byte[] timestamp;

	@NotNull
	@Component(6)
	public Long syncNum;


	public boolean equals(Object obj) {
		if(!(obj instanceof SmartStrategyRequestMessage)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static SmartStrategyRequestMessage ber_decode(InputStream in) throws IOException {
		return (SmartStrategyRequestMessage)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65608);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(SmartStrategyRequestMessage.class);
		AsnConverter msgCntConverter = MsgCount.CONV;
		AsnConverter tokenConverter = Token.CONV;
		AsnConverter vidConverter = OctetStringConverter.INSTANCE;
		AsnConverter drivebehaviorConverter = DRIVEBEHAVIOR.CONV;
		AsnConverter movingdissConverter = FLOAT.CONV;
		AsnConverter timestampConverter = TimeStamp.CONV;
		AsnConverter syncNumConverter = LongConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { msgCntConverter, tokenConverter, vidConverter, drivebehaviorConverter, movingdissConverter, timestampConverter, syncNumConverter });
	}


}
