/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.car;

import java.io.*;
import java.math.*;
import java.util.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

import com.iot.nero.smartcan.entity.Platoon;
public class SmartRecognizeRequestMessage {

	@NotNull
	@Component(0)
	public Long msgCnt;

	@NotNull
	@Component(1)
	public byte[] token;

	@NotNull
	@Size(min=8, max=8)
	@Component(2)
	public byte[] vid;

	@NotNull
	@Component(3)
	public Vector<RecongnizeObject> recongnizeobject;

	@NotNull
	@Component(4)
	public Position3D position;

	@NotNull
	@Component(5)
	public byte[] timestamp;

	@NotNull
	@Component(6)
	public Long syncNum;


	public boolean equals(Object obj) {
		if(!(obj instanceof SmartRecognizeRequestMessage)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static SmartRecognizeRequestMessage ber_decode(InputStream in) throws IOException {
		return (SmartRecognizeRequestMessage)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65599);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(SmartRecognizeRequestMessage.class);
		AsnConverter msgCntConverter = MsgCount.CONV;
		AsnConverter tokenConverter = Token.CONV;
		AsnConverter vidConverter = OctetStringConverter.INSTANCE;
		AsnConverter recongnizeobjectConverter = new VectorConverter(RecongnizeObject.CONV);
		AsnConverter positionConverter = Position3D.CONV;
		AsnConverter timestampConverter = TimeStamp.CONV;
		AsnConverter syncNumConverter = LongConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { msgCntConverter, tokenConverter, vidConverter, recongnizeobjectConverter, positionConverter, timestampConverter, syncNumConverter });
	}


}
