/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.car;

import java.io.*;
import java.math.*;
import java.util.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

import com.iot.nero.smartcan.entity.Platoon;
public class SmartDissolveRequestMessage {

	@NotNull
	@Component(0)
	public Long msgCount;

	@NotNull
	@Component(1)
	public byte[] token;

	@NotNull
	@Size(min=8, max=8)
	@Component(2)
	public byte[] id;

	@NotNull
	@Component(3)
	public byte[] endtime;

	@NotNull
	@Component(4)
	public Long vehicleCount;

	@NotNull
	@Component(5)
	public Vector<byte[]> vehicleList;

	@NotNull
	@Component(6)
	public byte[] timestamp;

	@NotNull
	@Component(7)
	public Long syncNum;


	public boolean equals(Object obj) {
		if(!(obj instanceof SmartDissolveRequestMessage)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static SmartDissolveRequestMessage ber_decode(InputStream in) throws IOException {
		return (SmartDissolveRequestMessage)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65621);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(SmartDissolveRequestMessage.class);
		AsnConverter msgCountConverter = MsgCount.CONV;
		AsnConverter tokenConverter = Token.CONV;
		AsnConverter idConverter = OctetStringConverter.INSTANCE;
		AsnConverter endtimeConverter = TimeStamp.CONV;
		AsnConverter vehicleCountConverter = LongConverter.INSTANCE;
		AsnConverter vehicleListConverter = VehicleList.CONV;
		AsnConverter timestampConverter = TimeStamp.CONV;
		AsnConverter syncNumConverter = LongConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { msgCountConverter, tokenConverter, idConverter, endtimeConverter, vehicleCountConverter, vehicleListConverter, timestampConverter, syncNumConverter });
	}


}
