/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.car;

import java.io.*;
import java.util.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import com.iot.nero.smartcan.entity.Platoon;

public class SmartFromATeamRequestMessage {

	@NotNull
	@Component(0)
	public Long msgCount;

	@NotNull
	@Component(1)
	public byte[] token;

	@NotNull
	@Component(2)
	public byte[] time;

	@NotNull
	@Component(3)
	public Long vehicleCount;

	@NotNull
	@Component(4)
	public Position3D startPosition;

	@NotNull
	@Component(5)
	public Position3D endPosition;

	@NotNull
	@Component(6)
	public Vector<byte[]> vehicleList;

	@NotNull
	@Component(7)
	public Position3D position;

	@NotNull
	@Component(8)
	public byte[] timestamp;

	@NotNull
	@Component(9)
	public Long syncNum;


	public boolean equals(Object obj) {
		if(!(obj instanceof SmartFromATeamRequestMessage)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static SmartFromATeamRequestMessage ber_decode(InputStream in) throws IOException {
		return (SmartFromATeamRequestMessage)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65616);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(SmartFromATeamRequestMessage.class);
		AsnConverter msgCountConverter = MsgCount.CONV;
		AsnConverter tokenConverter = Token.CONV;
		AsnConverter timeConverter = TimeStamp.CONV;
		AsnConverter vehicleCountConverter = LongConverter.INSTANCE;
		AsnConverter startPositionConverter = Position3D.CONV;
		AsnConverter endPositionConverter = Position3D.CONV;
		AsnConverter vehicleListConverter = VehicleList.CONV;
		AsnConverter positionConverter = Position3D.CONV;
		AsnConverter timestampConverter = TimeStamp.CONV;
		AsnConverter syncNumConverter = LongConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { msgCountConverter, tokenConverter, timeConverter, vehicleCountConverter, startPositionConverter, endPositionConverter, vehicleListConverter, positionConverter, timestampConverter, syncNumConverter });
	}


}
