/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.platoon;

import java.io.*;

import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;

public class LoginRequestMessage {

	@Component(0)
	public Long msgCnt;

	@Component(1)
	public byte[] iccid;	/* OPTIONAL */

	@Component(2)
	public byte[] imsi;	/* OPTIONAL */

	@Component(3)
	public byte[] imei;	/* OPTIONAL */

	@Component(4)
	public Long syncNum;


	public boolean equals(Object obj) {
		if(!(obj instanceof LoginRequestMessage)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONV, out);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static LoginRequestMessage ber_decode(InputStream in) throws IOException {
		return (LoginRequestMessage)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65542);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(LoginRequestMessage.class);
		AsnConverter msgCntConverter = LongConverter.INSTANCE;
		AsnConverter iccidConverter = OctetStringConverter.INSTANCE;
		AsnConverter imsiConverter = OctetStringConverter.INSTANCE;
		AsnConverter imeiConverter = OctetStringConverter.INSTANCE;
		AsnConverter syncNumConverter = LongConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { msgCntConverter, iccidConverter, imsiConverter, imeiConverter, syncNumConverter });
	}


}
