/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.platoon;

import java.io.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;

public class Position3D {

	@Component(0)
	public Double longitude;

	@Component(1)
	public Double latitude;

	@Component(2)
	public Double velocity;

	@Component(3)
	public Double yaw;

	@Component(4)
	public Double altitude;

	@Component(5)
	public byte[] gpsUtime;


	public boolean equals(Object obj) {
		if(!(obj instanceof Position3D)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONV, out);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static Position3D ber_decode(InputStream in) throws IOException {
		return (Position3D)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65540);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(Position3D.class);
		AsnConverter longitudeConverter = DoubleConverter.INSTANCE;
		AsnConverter latitudeConverter = DoubleConverter.INSTANCE;
		AsnConverter velocityConverter = DoubleConverter.INSTANCE;
		AsnConverter yawConverter = DoubleConverter.INSTANCE;
		AsnConverter altitudeConverter = DoubleConverter.INSTANCE;
		AsnConverter gpsUtimeConverter = TimeStamp.CONV;
		CONV.setComponentConverters(new AsnConverter[] { longitudeConverter, latitudeConverter, velocityConverter, yawConverter, altitudeConverter, gpsUtimeConverter });
	}


}
