/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.platoon;

import java.io.*;

import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;

public class SmartCanRequestBody {

	@Component(0)
	public Long msgCnt;

	@Component(1)
	public byte[] token;

	@Component(2)
	public byte[] vid;

	@Component(3)
	public Wiper wipers;

	@Component(4)
	public Light lights;

	@Component(5)
	public Running runnings;

	@Component(6)
	public Safety safetys;

	@Component(7)
	public Other others;

	@Component(8)
	public byte[] timestamp;

	@Component(9)
	public Long syncNum;


	public boolean equals(Object obj) {
		if(!(obj instanceof SmartCanRequestBody)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONV, out);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static SmartCanRequestBody ber_decode(InputStream in) throws IOException {
		return (SmartCanRequestBody)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65579);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(SmartCanRequestBody.class);
		AsnConverter msgCntConverter = LongConverter.INSTANCE;
		AsnConverter tokenConverter = Token.CONV;
		AsnConverter vidConverter = OctetStringConverter.INSTANCE;
		AsnConverter wipersConverter = Wiper.CONV;
		AsnConverter lightsConverter = Light.CONV;
		AsnConverter runningsConverter = Running.CONV;
		AsnConverter safetysConverter = Safety.CONV;
		AsnConverter othersConverter = Other.CONV;
		AsnConverter timestampConverter = TimeStamp.CONV;
		AsnConverter syncNumConverter = LongConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { msgCntConverter, tokenConverter, vidConverter, wipersConverter, lightsConverter, runningsConverter, safetysConverter, othersConverter, timestampConverter, syncNumConverter });
	}


}
