/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.platoon;

import java.io.*;

import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;

public class SmartStrategyRequestMessage {

	@Component(0)
	public Long msgCnt;

	@Component(1)
	public byte[] token;

	@Component(2)
	public byte[] vid;

	@Component(3)
	public DRIVEBEHAVIOR drivebehavior;

	@Component(4)
	public Double movingdiss;

	@Component(5)
	public byte[] timestamp;

	@Component(6)
	public Long syncNum;


	public boolean equals(Object obj) {
		if(!(obj instanceof SmartStrategyRequestMessage)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONV, out);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static SmartStrategyRequestMessage ber_decode(InputStream in) throws IOException {
		return (SmartStrategyRequestMessage)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65592);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(SmartStrategyRequestMessage.class);
		AsnConverter msgCntConverter = LongConverter.INSTANCE;
		AsnConverter tokenConverter = Token.CONV;
		AsnConverter vidConverter = OctetStringConverter.INSTANCE;
		AsnConverter drivebehaviorConverter = DRIVEBEHAVIOR.CONV;
		AsnConverter movingdissConverter = DoubleConverter.INSTANCE;
		AsnConverter timestampConverter = TimeStamp.CONV;
		AsnConverter syncNumConverter = LongConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { msgCntConverter, tokenConverter, vidConverter, drivebehaviorConverter, movingdissConverter, timestampConverter, syncNumConverter });
	}


}
