/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.platoon;

import java.io.*;
import java.math.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class SmartTeamRequestMessage {

	@Component(0)
	public Long msgCount;

	@Component(1)
	public byte[] token;

	@Component(2)
	public byte[] vid;

	@Component(3)
	public ISFLEET isfleet;

	@Component(4)
	public byte[] id;

	@Component(5)
	public ROLE role;

	@Component(6)
	public Long vehiclenum;

	@Component(7)
	public Double frontdistance;

	@Component(8)
	public Double speed;

	@Component(9)
	public byte[] timestamp;

	@Component(10)
	public Long syncNum;


	public boolean equals(Object obj) {
		if(!(obj instanceof SmartTeamRequestMessage)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONV, out);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static SmartTeamRequestMessage ber_decode(InputStream in) throws IOException {
		return (SmartTeamRequestMessage)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65612);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(SmartTeamRequestMessage.class);
		AsnConverter msgCountConverter = LongConverter.INSTANCE;
		AsnConverter tokenConverter = Token.CONV;
		AsnConverter vidConverter = OctetStringConverter.INSTANCE;
		AsnConverter isfleetConverter = ISFLEET.CONV;
		AsnConverter idConverter = OctetStringConverter.INSTANCE;
		AsnConverter roleConverter = ROLE.CONV;
		AsnConverter vehiclenumConverter = LongConverter.INSTANCE;
		AsnConverter frontdistanceConverter = DoubleConverter.INSTANCE;
		AsnConverter speedConverter = DoubleConverter.INSTANCE;
		AsnConverter timestampConverter = TimeStamp.CONV;
		AsnConverter syncNumConverter = LongConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { msgCountConverter, tokenConverter, vidConverter, isfleetConverter, idConverter, roleConverter, vehiclenumConverter, frontdistanceConverter, speedConverter, timestampConverter, syncNumConverter });
	}


}
